app_id = 'xxxxx'
app_secret = 'xxxxx'
app_uri = 'xxxxx'
app_scopes = 'xxxxx'
app_ua='xxxxx'
app_account_code = 'xxxxx'
app_refresh = 'xxxxx'
account_sid = "xxxxx"
auth_token = "xxxxx"
ePhone = "+1xxxxxxxxxx"
